### ISSUE TITLE
Left nav current item arrow is missing

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#111]
Currently, when viewing a page with the left nav showing, there is a little arrow next to the current item to show you where you are. Not seeing that in dev.

Prod:
![image](https://cloud.githubusercontent.com/assets/8182013/3757423/f649a1e2-1838-11e4-83a3-731e6ded7560.png)

Dev:
![image](https://cloud.githubusercontent.com/assets/8182013/3757421/ec35b7a4-1838-11e4-880a-4faa1634f027.png)

**Comment by knice** [comment]
Closing this because it has to do with the **index block** settings. Making the change that fixes this error  adds additional pages to the left nav list.

I'd like to figure this one out, but it will have to go to services for now.
