### ISSUE TITLE
iPad and iPhone Dept/Div Homepage 2nd Row

### ISSUE THREAD

**Issue by luckyluke007** [ucsc/webtemplates2014#144]
![2nd-row-boxes](https://cloud.githubusercontent.com/assets/1154568/3785566/4dd1dc84-19c6-11e4-86d0-ab60601f07cc.jpg)

Dept and Div homepage - I think 2nd row boxes should be even with the whole layout.

http://summer-dev.ucsc.edu or http://chemistry-dev.ucsc.edu

**Comment by knice** [comment]
I have improved the spacing of these elements and deployed the fix to production. Closing this issue as this is as close as we can get to matching these elements. in width.

![block-widtha](https://cloud.githubusercontent.com/assets/36719/6239272/0ddaa802-b6b7-11e4-89e3-5ef1e063fa0e.png)
