### ISSUE TITLE
Search Box icon missing in Search Results page

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#157]
This is similar to issue #119, but this is for the additional search box that shows up on search results pages.
The familiar magnifying glass icon is missing from the search box in Dev. It still says "Search..." but in my opinion it's less clear without the icon. If this is intentional, it should be added to the Design Change list.
See: http://apo-dev.ucsc.edu/search.html?cx=009891836300427205563%3Aeo1v9thief4&cof=FORID%3A10&ie=UTF-8&q=Random&x=0&y=0

Prod:
![image](https://cloud.githubusercontent.com/assets/8182013/3791849/ee2e4c44-1b56-11e4-927d-f86720b4c4b9.png)

Dev:
![image](https://cloud.githubusercontent.com/assets/8182013/3791844/dfdec736-1b56-11e4-82e1-c05703c93cf6.png)

**Comment by knice** [comment]
Closing this. Showing the search icon is more likely to be confusing than helpful since the icon is so small. The search box in the header has not had a button icon since launch and--to my knowledge-- we have not had anyone mention it.
