### ISSUE TITLE
Spacing between bullets?  Can't tell but looks harder to read.

### ISSUE THREAD

**Issue by leslieg** [ucsc/webtemplates2014#190]
http://astro-dev.ucsc.edu/about_department/info_visitors/parking.html

![image](https://cloud.githubusercontent.com/assets/7796000/3914923/8445559a-2351-11e4-826d-91b2366a663c.png)

![image](https://cloud.githubusercontent.com/assets/7796000/3914926/90a23fce-2351-11e4-9d22-e6d77744cca7.png)

**Comment by knice** [comment]
Bumped `margin-bottom` on `dd` and `li` to `0.45em`

![screen shot 2015-01-21 at 10 55 20 am](https://cloud.githubusercontent.com/assets/36719/5842738/1f5f49d6-a15c-11e4-86f6-454b33efd073.png)
