### ISSUE TITLE
What does 3rd-level of left navigation look like?

### ISSUE THREAD

**Issue by knice** [ucsc/webtemplates2014#21]
Link to an example.

**Comment by knice** [comment]
I've deployed a stylesheet update to address this issue. Second and third-level links now have styles that distinguish them from each other. Additionally, the current link text is bold to help indicate what page you are on. 

Rob's note: This also required a format change to `_library/formats/Left Nav`

### Before

![image](https://cloud.githubusercontent.com/assets/8182013/4018740/facb8c62-2a53-11e4-8f69-a90f8fadd1d1.png)

### Now

(User is on a second-level page and the third-level nav is revealed)

![screen shot 2015-04-17 at 2 38 04 pm](https://cloud.githubusercontent.com/assets/36719/7211478/01e476c2-e510-11e4-9dc4-994e55aa4dd2.png)

(User is on a third-level page and the current page in the third-level nav is indicated in bold)

![screen shot 2015-04-17 at 2 37 53 pm](https://cloud.githubusercontent.com/assets/36719/7211491/1dda3434-e510-11e4-9257-65b139d0a129.png)

**Comment by knice** [comment]
![left-column-improvement](https://cloud.githubusercontent.com/assets/36719/7211907/c78b9a14-e514-11e4-91f0-cb425a18edc3.png)

**Comment by dajoturner** [comment]
Thanks. Thought I closed this one earlier this week. I tested, looks great.
