### ISSUE TITLE
Left nav block - global header bold (nice) but local block header not bold

### ISSUE THREAD

**Issue by leslieg** [ucsc/webtemplates2014#231]
Dont' have an example of how it is now.

![image](https://cloud.githubusercontent.com/assets/7796000/3936065/e19f1d1a-249c-11e4-8c48-b6ed6c43d4f4.png)

**Comment by knice** [comment]
Confirmed this is fixed on prod. It will take affect after a left nav page is published from here on.

Changed `<h4>` to `<h4 class="block-header">` on line 11 of left nav page block format.

![screen shot 2015-02-18 at 8 58 18 am](https://cloud.githubusercontent.com/assets/36719/6252101/bc565f6c-b74c-11e4-8f6b-8e04ada58c4d.png)
