### ISSUE TITLE
Gallery Page: Gallery item's caption not responsive/get's cut off

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/webtemplates2014#241]
http://astro-dev.ucsc.edu/about_department/image_gallery/gallery-page_research.html

Need to have a REALLY wide screen to view the caption
![2014-08-19_16-37-21](https://cloud.githubusercontent.com/assets/7795841/3974756/d07ddad4-27f9-11e4-9c14-183d7a1ff549.png)

**Comment by knice** [comment]
Ugh. Fixing this means fixing `local-html-head-gallery` on every site. This is not easy.

**Comment by teresasilva71** [comment]
Well, what we could do going forward is insert a character limit. That doesn't help the existing ones tho but it'll help it going forward. Just a thought.

**Comment by dajoturner** [comment]
Closing with the rest of Handoff to Svcs

**Comment by knice** [comment]
OK, this is fixed and deployed.

![screen shot 2015-04-06 at 2 28 17 pm](https://cloud.githubusercontent.com/assets/36719/7013107/7932ea40-dc6b-11e4-836b-2c8815263f8b.png)

**Comment by knice** [comment]
Confirmed it is now fixed on mobile devices as well.

![screen shot 2015-04-06 at 3 14 01 pm](https://cloud.githubusercontent.com/assets/36719/7013589/9d8df4ee-dc6f-11e4-8a87-330d56855893.png)

**Comment by teresasilva71** [comment]
Fixed except it's a small design change. I'll need to update my materials with the new look. Also, sites' gallery pages will need to be republished for it to work. :)

**Comment by dajoturner** [comment]
Note: Rob fixed this on 4/6/15. Nice job Rob!

**Comment by knice** [comment]
@teresasilva71 Sites gallery pages **do not** need to be republished for this to take effect. This was a CSS change so it will take effect as soon as the user's browser downloads the updated stylesheet (some browsers cache stylesheets for a few days).
