### ISSUE TITLE
White Scrolling Bars on side and bottom of pages

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/webtemplates2014#252]
Hi guys, there are 5 issues here that all relate to the weird unnecessary scroll bars

#100, #108 , #121 , #163 , and #200 

Rather than going around and around about them?  :) 

Let's consolidate. Don't know how to technically merge them all tho.

**Comment by knice** [comment]
Setting `overflow-x` to `auto` makes scroll bars only show up when the page is too narrow to properly show the content. Scroll bars no longer show up by default.
