### ISSUE TITLE
Profile lead image scaling up too large

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#308]
Looks like the Lead Image on the Profile page is acting weird.
See: http://emergency-mobile.ucsc.edu/news-events/profiles/gaylord-profile.html

Prod:
![image](https://cloud.githubusercontent.com/assets/8182013/4103334/4b98da00-3157-11e4-9a0c-0e818b8d08f5.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/8182013/4103336/5b0b9f90-3157-11e4-87fe-1a9447c3ee42.png)

**Comment by dajoturner** [comment]
@knice I still have an open incident for this, and I know that it's important to a lot of our users. Can you update this issue with your current thinking - can we get this done, or does it need to go to services for future work?

**Comment by knice** [comment]
I have been guilted (to the point of near-shame) into closing this ticket.

**Comment by dajoturner** [comment]
Not sufficient guilt for an update though?

I can't really test this one, because each of the examples that we have are different now - with no versions going back that far to look at. 

Did we do anything to address this, or just close the issue? I'm pressing because I need to respond back to an incident.

**Comment by knice** [comment]
I've just published a fix for [this issue][1] and similarly, [this issue][2]. Images in callout boxes no longer scale up to 100% width by default. They stay at the natural size of the image.

[1]: https://github.com/ucsc/webtemplates2014/issues/308#issuecomment-54236918
[2]: https://github.com/ucsc/webtemplates2014/issues/308#issuecomment-54990848

![screen shot 2015-04-09 at 6 25 22 pm](https://cloud.githubusercontent.com/assets/36719/7080372/d70b0a2c-dee5-11e4-97a4-cf0f625d4a5b.png)

**Comment by dajoturner** [comment]
Waiting for Julie to test. Response will come under INC0205053.

**Comment by knice** [comment]
With the commit I just made (sets image sizes in articles and profiles) and Julie's issue resolved, I am closing this issue.

**Comment by knice** [comment]
@teresasilva71 with regard to [this comment](https://github.com/ucsc/webtemplates2014/issues/308#issuecomment-60270563): I was not aware of the problem with profile images in **home page** profile blocks. In the process of getting the CIED website ready for launch, I discovered that problem. 

I'm **so sorry** I didn't fully understand that issue sooner (In this thread, I was focused on the images in profile _pages_, not blocks). It is now resolved. An example is on the [CIED home page](http://cied.ucsc.edu).
