### ISSUE TITLE
Link from home page banner image does not work

### ISSUE THREAD

**Issue by thomasgardner** [ucsc/webtemplates2014#337]
On the Economics home page a link from one of their banner images does not work, i.e. http://economics.ucsc.edu/ (banner image 1)
How it looks in Cascade (Note: I tried switching it from a manual URL to an internal link and it still didn't work.)
![screen shot 2014-09-09 at 3 04 15 pm](https://cloud.githubusercontent.com/assets/1775933/4209794/ae8d9052-386d-11e4-9c74-689ded0e4e85.png)

**Comment by knice** [comment]
If there is a link, billboard is linked.

![napkin 2 04-13-15 1 00 09 pm](https://cloud.githubusercontent.com/assets/36719/7124625/6f8c334c-e1df-11e4-918a-44cae5d1d578.png)

**Comment by knice** [comment]
Note: existing pages will need to be republished to see this change.

**Comment by dajoturner** [comment]
awesome, thanks Rob
