### ISSUE TITLE
Left Nav: Left navigation disappears when a faculty category feed doesn't populate

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/webtemplates2014#343]
It used to be that the left nav would stay, now it goes away.

TRUE, the site should have those categories un-indexed so those pages don't appear but they don't always do that.

lals.ucsc.edu
legalstudies.ucsc.edu
psychology.ucsc.edu

to name a few that I spot checked
![faculty](https://cloud.githubusercontent.com/assets/7795841/4254129/07c2d5a6-3aa8-11e4-8bdc-be57746d39f7.png)
![faculty-no-nav](https://cloud.githubusercontent.com/assets/7795841/4254131/0b4b5ff4-3aa8-11e4-83f4-ed12282459f9.png)

**Comment by leslieg** [comment]
I wonder if this is also happening for the course feed.  The database connection to AIS went down today and I noticed that the left nav disappeared on those pages.

**Comment by knice** [comment]
I imagine both pages are setup the same way. If the feed is blank, the PHP
script terminates and the left column never loads. It should be
reconfigured to move on, rather than terminate.

**Comment by knice** [comment]
This change has been made on dev, so I think it is safe to make it in production. @thomasgardner, can you make this change some time in the next few days? I'd like to close this ticket in the next week.

**Comment by knice** [comment]
Here is a page you can use to test the change: http://psychology.ucsc.edu/faculty/visiting-scholars.php

I'd make this change myself, but I do not remember how to escalate my privileges so I have permission to edit the appropriate file.

**Comment by knice** [comment]
@thomasgardner fixed this, because he is awesome. Thank you, Tom!
