### ISSUE TITLE
Printed pages need URL and print date in footer

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#345]
Christina Navarro reported this issue (INC0205133). Was there a reason not to include address and date on prints?

Christina said:
The page prints with the content, but the print version no longer shows the url for where it was printed from and the date. I think that was useful information and would ask that be included in the programmed print layout.

**Comment by dajoturner** [comment]
@knice I still have an open incident for this, and I know that it's important to a lot of our users. Can you update this issue with your current thinking - can we get this done, or does it need to go to services for future work?

**Comment by knice** [comment]
This has been fixed and the updated has been deployed to production. Confirmed in Safari, Firefox, and Chrome (latest releases), headers and footers appear and do not interfere with page content.

This was fixed using the [`@page` CSS at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@page)

![chrome-headers-footers](https://cloud.githubusercontent.com/assets/36719/6238397/770da0a2-b6af-11e4-9fe3-5bf42aa984b5.png)

**Comment by dajoturner** [comment]
Woo hoo! Thanks Rob
