### ISSUE TITLE
Firefox dropdown menu issue

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#346]
Mitchell Mastroni reported this issue (INC0207457). Glitch in Firefox - sounds like he's done his research, but I haven't been able to verify. I've asked him for a link.

Michael said:
All web pages that use the current version of the UCSC responsive stylesheet (http://static.ucsc.edu/_responsive/css/ucsc.css) have a small display error on Firefox. The drop down menu isn't formatted properly and as a result it takes up almost the entire screen. This can be fixed by removing the line 2848, 'width:100%' under #mainNav li ul. As far as I can tell, this doesn't affect the formatting on any browser other than fixing Firefox.

**Comment by knice** [comment]
Confirmed this is fixed in Firefox 16 (Win8).

![screen shot 2015-02-18 at 8 22 42 am](https://cloud.githubusercontent.com/assets/36719/6251222/7df0a958-b747-11e4-8c79-58f08636e1b9.png)
