### ISSUE TITLE
2 Search boxes on iPhones

### ISSUE THREAD

**Issue by claucasf** [ucsc/webtemplates2014#348]
![two search boxes](https://cloud.githubusercontent.com/assets/8648003/4598684/f4c7d2c4-50bb-11e4-96f1-6f15b486500d.png)

**Comment by knice** [comment]
Second search box is hidden on touch-enabled mobile devices.

Developer note: I used a hook from Modernizr (`.touch`) as a style hook to hide the second search box.

![screen shot 2015-05-27 at 5 33 58 pm](https://cloud.githubusercontent.com/assets/36719/7850422/fc560314-0496-11e5-9c30-1ebe47b07829.png)
![screen shot 2015-05-27 at 5 31 40 pm](https://cloud.githubusercontent.com/assets/36719/7850421/fc552b1a-0496-11e5-8869-c2e26e6f80a4.png)
