### ISSUE TITLE
Text and Search Boxes getting cut off on iPhone

### ISSUE THREAD

**Issue by claucasf** [ucsc/webtemplates2014#349]
![search bar cutoff](https://cloud.githubusercontent.com/assets/8648003/4598718/57377ffe-50bc-11e4-9a92-6550187f6b45.png)

**Comment by knice** [comment]
This is fixed.

![screen shot 2015-01-21 at 1 26 08 pm](https://cloud.githubusercontent.com/assets/36719/5845479/29115ba8-a171-11e4-96b2-4da710d452e1.png)
