### ISSUE TITLE
Extra line between list bullets in WCMS/Campus Directory listing

### ISSUE THREAD

**Issue by thomasgardner** [ucsc/webtemplates2014#362]
In ITRequest INC0385048 Professor Glenn Millhauser noted that extra lines are inserted between the bullet points in his listing at http://www.chemistry.ucsc.edu/faculty/singleton.php?singleton=true&cruz_id=glennm

**Comment by knice** [comment]
I took a look at this. This is not a template or stylesheet issue. There is actually a line break after each bullet in Glenn's list. It is in the HTML source for the page.

So this is not an issue we can fix in the stylesheet, it needs to be fixed where ever the HTML is created.

![screen shot 2016-06-14 at 1 57 28 pm](https://cloud.githubusercontent.com/assets/36719/16059607/741a0fd8-3238-11e6-9b2b-4b9b7cea7402.png)

**Comment by thomasgardner** [comment]
Hey Rob,
Thanks for investigating. I'll check with the IDM group as that's where the data is originating.
-Tom
